name: Smart Contract CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/eth-contracts/**'
  pull_request:
    paths:
      - 'apps/eth-contracts/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/eth-contracts

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check contract sizes
        run: npx hardhat size-contracts

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run solhint
        run: npx solhint 'contracts/**/*.sol'

      - name: Check formatting
        run: npx prettier --check 'contracts/**/*.sol'

  # Keeping test job commented out for future implementation
  # test:
  #   needs: validate
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: apps/eth-contracts
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         cache: 'npm'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run tests
  #       run: npx hardhat test
